name: Python Project Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: integeration_test
    env:
      RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
      SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      APIM_INSTANCE: ${{ vars.APIM_INSTANCE }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Load Dependencies
        shell: bash
        run: |
          set -e # fail on error
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Integration Tests
        shell: bash
        run: |
          pytest tests/integration --cov=.

      - name: Generate Coverage Report
        shell: bash
        run: |
          coverage html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Display Coverage Report
        if: always()
        run: |
          echo "Coverage report generated. To view the report, download the 'coverage-report' artifact and open the index.html file in a web browser."
