name: Deploy APIs to APIM

on:
  push:
    branches:
      - master
    paths:
      - 'apis/**'
      - 'environments/**'
      - 'deployment/**'
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: ${{ secrets.DEV_RESOURCE_GROUP }}
      SUBSCRIPTION_ID: ${{ secrets.DEV_SUBSCRIPTION_ID }}
      APIM_INSTANCE: euw-int-ai-dev-genai-apim
      ENVIRONMENT: dev
    steps:
      - name: 'Az CLI login '
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DEV_CLIENT_ID }}
          tenant-id: ${{ secrets.DEV_TENANT_ID }}
          subscription-id: ${{ secrets.DEV_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL
          enable-AzPSSession: true
      - name: 'Run az commands'
        run: |
          az account show
          az group list
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy APIs
        env:
          APIM_INSTANCE: euw-int-ai-dev-genai-apim
          ENVIRONMENT: dev
        run: |
          python api_management/main.py
